/* automatically generated by rust-bindgen 0.58.1 */

extern "C" {
    pub fn rdft(
        n: ::std::os::raw::c_int,
        isgn: ::std::os::raw::c_int,
        a: *mut f64,
        ip: *mut ::std::os::raw::c_int,
        w: *mut f64,
    );
}
extern "C" {
    pub fn ddct(
        n: ::std::os::raw::c_int,
        isgn: ::std::os::raw::c_int,
        a: *mut f64,
        ip: *mut ::std::os::raw::c_int,
        w: *mut f64,
    );
}
